-- AlterTable
ALTER TABLE "students_data" ALTER COLUMN "anak_keberapa" SET DATA TYPE TEXT,
ALTER COLUMN "jumlah_saudara_kandung" SET DATA TYPE TEXT,
ALTER COLUMN "jumlah_saudara_tiri" SET DATA TYPE TEXT,
ALTER COLUMN "jumlah_saudara_angkat" SET DATA TYPE TEXT,
ALTER COLUMN "nomor_telepon" SET DATA TYPE TEXT,
ALTER COLUMN "jarak_tempat_tinggal_ke_sekolah" SET DATA TYPE TEXT,
ALTER COLUMN "tinggi_dan_berat_badan_saat_diterima" SET DATA TYPE TEXT,
ALTER COLUMN "semester" SET DATA TYPE TEXT,
ALTER COLUMN "berat_badan" SET DATA TYPE TEXT,
ALTER COLUMN "tinggi_badan" SET DATA TYPE TEXT,
ALTER COLUMN "nis" SET DATA TYPE TEXT,
ALTER COLUMN "diterima_saat_kelas" SET DATA TYPE TEXT,
ALTER COLUMN "tahu_lahir_ibu" SET DATA TYPE TEXT,
ALTER COLUMN "tahun_lahir_wali" SET DATA TYPE TEXT,
ALTER COLUMN "kelas_sekarang" SET DATA TYPE TEXT,
ALTER COLUMN "dari_kelas" SET DATA TYPE TEXT,
ALTER COLUMN "kelas_yang_ditinggalkan" SET DATA TYPE TEXT,
ALTER COLUMN "nomor_ijasah" SET DATA TYPE TEXT,
ALTER COLUMN "tahun_lahir_ayah" SET DATA TYPE TEXT;
