-- CreateTable
CREATE TABLE "students_data" (
    "id" SERIAL NOT NULL,
    "id_user" INTEGER NOT NULL,
    "nama_lengkap" TEXT NOT NULL,
    "nama_panggilan" TEXT NOT NULL,
    "jenis_kelamin" TEXT NOT NULL,
    "tempat_tanggal_lahir" TEXT NOT NULL,
    "agama" TEXT NOT NULL,
    "kewarganegaraan" TEXT NOT NULL,
    "anak_keberapa" INTEGER NOT NULL,
    "jumlah_saudara_kandung" INTEGER NOT NULL,
    "jumlah_saudara_tiri" INTEGER NOT NULL,
    "jumlah_saudara_angkat" INTEGER NOT NULL,
    "bahasa_sehari_hari" TEXT NOT NULL,
    "alamat" TEXT NOT NULL,
    "nomor_telepon" INTEGER NOT NULL,
    "bertempat_tinggal_bersama" TEXT NOT NULL,
    "jarak_tempat_tinggal_ke_sekolah" INTEGER NOT NULL,
    "golongan_darah" TEXT NOT NULL,
    "penyakit_yang_pernah_diderita" TEXT NOT NULL,
    "kelainan_jasmani" TEXT NOT NULL,
    "tinggi_dan_berat_badan_saat_diterima" INTEGER NOT NULL,
    "tahun_pelajaran" INTEGER NOT NULL,
    "semester" INTEGER NOT NULL,
    "berat_badan" INTEGER NOT NULL,
    "tinggi_badan" INTEGER NOT NULL,
    "asal_murid" TEXT NOT NULL,
    "nama_tk" TEXT NOT NULL,
    "alamat_tk" TEXT NOT NULL,
    "tanggal_dan_nomor_sstb" TEXT NOT NULL,
    "nama_sekolah_asal" TEXT NOT NULL,
    "dari_tingkat_kelas" TEXT NOT NULL,
    "nis" INTEGER NOT NULL,
    "alasan_pindah" TEXT NOT NULL,
    "diterima_tanggal" TEXT NOT NULL,
    "diterima_saat_kelas" INTEGER NOT NULL,
    "nama_ayah" TEXT NOT NULL,
    "tahu_lahir_ayah" INTEGER NOT NULL,
    "agama_ayah" TEXT NOT NULL,
    "pendidikan_ayah" TEXT NOT NULL,
    "pekerjaan_ayah" TEXT NOT NULL,
    "nama_ibu" TEXT NOT NULL,
    "tahu_lahir_ibu" INTEGER NOT NULL,
    "agama_ibu" TEXT NOT NULL,
    "pendidikan_ibu" TEXT NOT NULL,
    "pekerjaan_ibu" TEXT NOT NULL,
    "nama_wali" TEXT NOT NULL,
    "tahun_lahir_wali" INTEGER NOT NULL,
    "agama_wali" TEXT NOT NULL,
    "pendidikan_wali" TEXT NOT NULL,
    "pekerjaan_wali" TEXT NOT NULL,
    "alamat_wali" TEXT NOT NULL,
    "hubungan_keluarga_wali" TEXT NOT NULL,
    "tahun_sekarang" TEXT NOT NULL,
    "kelas_sekarang" INTEGER NOT NULL,
    "dari_kelas" INTEGER NOT NULL,
    "tanggal_meninggalkan_sekolah" TEXT NOT NULL,
    "kelas_yang_ditinggalkan" INTEGER NOT NULL,
    "alasan_meninggalkan_sekolah" TEXT NOT NULL,
    "sekolah_yang_dituju" TEXT NOT NULL,
    "kecamatan_sekolah_tujuan" TEXT NOT NULL,
    "kabupaten_sekolah_tujuan" TEXT NOT NULL,
    "provinsi_sekolah_tujuan" TEXT NOT NULL,
    "tempat_belajar" TEXT NOT NULL,
    "nomor_ijasah" TEXT NOT NULL,
    "akan_melanjutkan_ke" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "students_data_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "students_data" ADD CONSTRAINT "students_data_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
